services:
  catalogdb:
    image: postgres:17
  basketDb:
    image: postgres:17

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: eshop-microservices/Catalog.API/Dockerfile

volumes:
  postgres_dev1_catalog:  
  postgres_dev1_basket:  

